---

- name: ensure youtube-dl is installed
  become: yes
  pip:
    name: youtube-dl

- name: make directory
  become: no
  file:
    state: directory
    owner: steven
    path: ~/morningmix

- name: download morning mix
  become: no
  shell: youtube-dl "https://www.youtube.com/watch?v=FxzBvqY5PP0&list=PLTG6XJDnYHAcMd3-qKSjgd3rTtW7D95aw"
  args:
    chdir: ~/morningmix

- name: ensure vlc is installed
  become: yes
  apt:
    name: vlc

- name: add to favorites
  become: no
  shell: gsettings set com.canonical.Unity.Launcher favorites "$(gsettings get com.canonical.Unity.Launcher favorites | sed "s/, *'vlc.desktop' *//g" | sed "s/'vlc.desktop' *, *//g" | sed -e "s/]$/, 'vlc.desktop']/")"

- name: set up alarm clock
  cron:
    name: "alarm clock"
    weekday: 1-5 #this means weekdays only
    #user: steven
    job: /usr/bin/vlc $(ls /home/steven/morningmix | shuf -n 1)
    hour: 18
    minute: 20
