#Generated by Kickstart Configurator
#platform=x86

#System language
lang en_US
#Language modules to install
langsupport en_US
#System keyboard
keyboard us
#System mouse
mouse
#System timezone
timezone America/New_York
#Root password
rootpw --disabled
#Initial user
user steven --fullname "steven" --iscrypted --password $1$RRrBjN..$4OhdezOsC0dV9jzRNMhfy.
#Reboot after installation
reboot
#Use text mode install
text
#Install OS instead of upgrade
install
#Use CDROM installation media
cdrom
#System bootloader configuration
bootloader --location=mbr 
#Clear the Master Boot Record
zerombr yes
#Partition clearing information
clearpart --all --initlabel 
#System authorization infomation
auth  --useshadow  --enablemd5 
#Firewall configuration
firewall --disabled --ssh 
#Do not configure the X Window System
skipx
#Package install information
%packages
@ kubuntu-desktop
%post --interpreter=/bin/bash
#this is a read-only key for a public repository. don't panic
echo "
cat > /publicreporeadonly <<- EOM
-----BEGIN RSA PRIVATE KEY-----
MIIEpgIBAAKCAQEAt5LYL1Ra6vUH+GFR+tMwvph5YLFa2mhfRWjwUy4sY1XBHcim
uPSztTCYbfpO1QtLb/GXk0sEyoYmadzaCakmMmQPMg90CrY5oyetoVH94KZBvbC+
AFVVrGZtskCX1S67wkPbywm4IHoBwbUn0C7hD5ryoUy2ARg9zs8vE1FVGJlXOEgd
T1JwE5gekKXnwdkpxFrNqCSnC5rq39460My78miYcRkDyomvpEcRdp8igV3od/vc
MoIwA2fxgAxER5T7yyHB4xgAS+qG7gkFJZRNgL3wg7I6JAQxBtOCYxo2JPq/WA9B
ZXNjibTWCm1X/1LrlmRBT3nVZy4kJMnC6PzCHQIDAQABAoIBAQCzlbtZ6esbqeRH
L2XUvCAWhPFRD4/y1GJHc9aPeT9BWlYW/gFkNTdNDSJBjLrsHiWJeM4w8RXZzozr
yXugMdLFPy/CaG28QPJ300w/4gc8a0kq+imWB+VNR9MOq7QdgJ9794igw3xWgSUQ
zFkLh6Dy9EFiXLo8rethUzwZaNqXuVo95ukNqypsrxI5i5C/gN9X0WgvFMyErM6Y
UwExFHi/9zT38p5mz5hDHQ9j9IdfeDGTG3CSjJ3V4wNCCRVRcBNCmZ3Mkxw22MN9
Vt6ReYBrD/C/Xf/H7ebkB3XXc5wn7Y7dVIayeo2yjqy7y4x7Hsl8n6TtQwmNxVPB
m4X3xuMhAoGBAOYBShwxryTIOrqhFxm/sus1bXHFnSj8AcW/72Thf75OuLm+C4JL
Lv5k3/9Faoy1csfrm+4J1GogwBqcU1L9y3L3mjisd+T7KfeQmkFkHJFlw13yyDHQ
obrM3HD3wS6CuXPhXpS1pgazloNB0SQt9p7gzBUC4fQOZFamy67NNzHVAoGBAMxS
KN1njfKLL6bIhQRO6VAER+5WGvMdybG4UEHyncHBYPUfiviOuytz/Aew0QDvdiEp
fDrInZulXEa4SzLqDgC3RZY6yVOm8rXK7xQXrubdFzPmZXIu39VLexRYtPYI5BeY
fShL5MK4VmlDFrqd/HZh02gAjTtXODOgyjlLKyspAoGBAIF7LFte5PhR+C3kTfri
3jhnZWttEiJmbCEFAiHKiH18F6YJBLWe2Z/A7hDo5Si9ZRaC3s9MnVX5hev1ITtR
QN1B4oIRJZW0h1WlBBHX5/U6Updq+6R/jOx6M4ctEoW6deh0cShKcmLHau4NeU1i
yrl6V6lkbAtWpsnZMEUBphbZAoGBALNPq1NbLQTdx8z8D1iPlExH5YSyBma0Dq0s
TysBLBe9iUS2EPU/9d0Vpept7459mNNToBXKuB6/iXL7C+u74twX+zbzknoaesi2
NwkQG8u53kILAZ6qqn97BaH+k5mUhfB7P+Ocbz/AHP22Bf1y5vxRsAGG8mtQiR8u
Disn39O5AoGBALXfr3LLn5ctAhsnpG6Q4z5JmPd47l4PL0taz4e8N8tsPgx9ps6K
LFKJsbjPbAMJnkjbYNdjer80cJvpGlDyBk9Do1bmCUjugeT4fg2Esmwi3be3V2U3
jygsCE7tZmiuqQp6N1ywrwBglel7d1lBrIld9Go5FQJ5EYKScshDudRA
-----END RSA PRIVATE KEY-----
EOM

apt-add-repository ppa:ansible/ansible
apt-get update
apt-get install -y \
	software-properties-common \
	git \
        ansible
ansible --version
mkdir -p /home/steven
cd /home/steven
git clone https://github.com/sjmiller609/homeinfra.git
#cd homeinfra
#ansible-playbook -i ./hosts.yaml deploy.yml
