---

- name: zero favorites
  become: no
  failed_when: false #fails if desktop is not installed, but that's ok
  shell: gsettings set com.canonical.Unity.Launcher favorites "[]" && sleep 2 # needs a sleep for some reason

- name: install packages typically used for development
  become: yes
  apt:
    name: "{{ item }}"
  with_items:
    - build-essential
    - software-properties-common
    - libssl-dev
    - libffi-dev
    - openssl
    - python-dev
    - python
    - python3
    - python-pip
    - python3-pip
    - python-virtualenv
    - tmux
    - htop
    - tree
    - nmap
    - vim
    - git

- name: setup vimrc
  become: yes
  lineinfile:
    path: /etc/vim/vimrc
    line: '{{ item }}'
  with_items:
    - set tabstop=4
    - set shiftwidth=4
    - set expandtab
    - set noautoindent
    - set nocindent
    - set nosmartindent
    - set scrolloff=23
    - filetype indent off
    - autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

- name: add to favorites
  become: no
  failed_when: false #fails if desktop is not installed, but that's ok
  shell: "gsettings set com.canonical.Unity.Launcher favorites \"$(gsettings get com.canonical.Unity.Launcher favorites | sed \"s/, *'{{ item }}' *//g\" | sed \"s/'{{ item }}' *, *//g\" | sed -e \"s/]$/, '{{ item }}']/\")\" && sleep 2"
  with_items:
    - terminal.desktop
    - htop.desktop
