---

- name: NVIDIA | Add repository for package owner
  become: yes
  apt_repository:
    repo: 'ppa:graphics-drivers'
    state: present
    update_cache: yes

- name: install driver
  become: yes
  apt:
    name: nvidia-384
  register: driver

- name: install nvidia configuration
  become: yes
  copy: 
    src: xorg.conf
    dest: /etc/X11/xorg.conf
    owner: root
    group: root
    mode: 0644
  register: conf1

- name: install nvidia configuration
  become: no
  copy: 
    src: xorg.conf
    dest: /home/steven/.nvidia-settings-rc
    owner: steven
    group: steven
    mode: 0644
  register: conf2

- name: install display configuration
  become: no
  copy: 
    src: monitors.xml
    dest: /home/steven/.config/monitors.xml
    owner: steven
    group: steven
    mode: 0644
  register: conf3

- name: determine what changed
  set_fact:
    restart_lightdm: driver.changed or conf1.changed or conf2.changed or conf3.changed

- debug: var=restart_lightdm

- name: restart lightdm
  become: yes
  when: restart_lightdm
  service:
    name: lightdm
    state: restarted
