---

- name: "ensure Google linux signing key present"
  become: yes
  apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present

- name: "ensure Google chrome repo present"
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    filename: "google-chrome"
    state: present
    update_cache: yes

- name: "ensure Google chrome present"
  become: yes
  apt:
    name: "google-chrome-stable"
    state: present

- name: add to favorites
  become: no
  shell: "gsettings set com.canonical.Unity.Launcher favorites \"$(gsettings get com.canonical.Unity.Launcher favorites | sed \"s/, *'{{ item }}' *//g\" | sed \"s/'{{ item }}' *, *//g\" | sed -e \"s/]$/, '{{ item }}']/\")\""
  with_items:
    - google-chrome.desktop
