---

- name: install desktop
  become: yes
  apt:
    name: ubuntu-desktop

- name: add to favorites
  become: no
  shell: "gsettings set com.canonical.Unity.Launcher favorites \"$(gsettings get com.canonical.Unity.Launcher favorites | sed \"s/, *'{{ item }}' *//g\" | sed \"s/'{{ item }}' *, *//g\" | sed -e \"s/]$/, '{{ item }}']/\")\""
  with_items:
    - nautilus.desktop
    - firefox.desktop
    - shutdown.desktop
    - libreoffice-startcenter.desktop
