---

- name: ensure youtube-dl is installed
  become: yes
  pip:
    name: youtube-dl
    state: latest

- name: clean out directory
  shell: "rm -rf /home/{{ username }}/morningmix"

- name: make directory
  become: no
  file:
    state: directory
    owner: "{{ username }}"
    path: "/home/{{ username }}/morningmix"

- name: download morning mix
  become: no
  shell: youtube-dl "https://www.youtube.com/watch?v=FxzBvqY5PP0&list=PLTG6XJDnYHAcMd3-qKSjgd3rTtW7D95aw"
  args:
    chdir: ~/morningmix

- name: set up alarm clock
  cron:
    name: "{{ item.name }}"
    weekday: "{{ item.weekdays }}"
    user: "{{ username }}"
    job: "{{ item.job }}"
    hour: "{{ item.hour }}"
    minute: "{{ item.minute }}"
  with_items:
    - weekdays: 1-5
      hour: 8
      minute: 0
      name: alarm clock
      job: "export DISPLAY=:0 && /usr/bin/vlc -LZ /home/{{ username }}/morningmix &"
    - weekdays: 1-5
      hour: 8
      minute: 30
      name: alarm clock off
      job: "pkill -15 vlc"
    - weekdays: 6,0
      hour: 10
      minute: 0
      name: alarm clock weekends
      job: "export DISPLAY=:0 && /usr/bin/vlc -LZ /home/{{ username }}/morningmix &"
    - weekdays: 0,6
      hour: 10
      minute: 30
      name: alarm clock weekends off
      job: "pkill -15 vlc"
